package types

type TagInfo struct {
	Name     string
	Desc     string
	Examples []string
	Contexts []string
}

var CommonModelTags = []TagInfo{
	{
		Name: "O",
		Desc: "The 'O' tag is used to indicate that a word or phrase does not belong to any specific named entity category. It is typically applied in contexts where the text does not contain any identifiable entities such as names, locations, organizations, or other specific identifiers. This tag helps in distinguishing between relevant entities and general text, allowing for clearer data processing and analysis. Recognizable patterns include words that do not follow the structure of names or titles, such as common nouns, verbs, or adjectives.",
		Examples: []string{
			"the", "and", "to", "of", "in", "a", "is", "was", "for", "on", "with", "as", "by", "at", "this", "that", "it", "from", "an", "be", "are", "not", "but", "or", "all", "any", "some", "no", "such", "more", "most", "much", "many",
		},
		Contexts: []string{
			"General text", "Common nouns", "Verbs", "Adjectives", "Prepositions", "Conjunctions", "Articles", "Pronouns", "Adverbs", "Interjections", "Punctuation marks", "Numbers", "Dates without specific entities", "Generic phrases", "Everyday language", "Informal speech", "Technical jargon without entities", "Legal disclaimers", "Scientific terms without entities", "Mathematical expressions",
		},
	},
	{
		Name: "NAME",
		Desc: "The 'NAME' tag is used for identifying and categorizing the individual identifiers of people, such as first names, last names, full names, or any combination thereof, as well as titles and honorifics. This tag is typically applied in contexts where personal identification is necessary, such as in lists, narratives, or databases. Recognizable patterns include capitalized words at the beginning of text or following titles (e.g., Dr., Mr., Ms.), or those that form common name structures, such as 'Maria Gomez'. Pay attention to formatting cues, cultural naming conventions, and context to accurately apply this tag.",
		Examples: []string{
			"Mr. James Harrison", "Professor Emily White", "Lieutenant Colonel Samuel P. Weston", "Lord Alfred Tennyson", "President Julio Martinez", "Miss Anna Lee", "Master Terry Smith", "Dr. A. B. Chandrakumar", "Sir Ian McKellen", "Madam C.J. Walker", "Mr. & Mrs. Johnson", "Chief Justice Roberts", "Captain Annabelle Knight", "Baroness Thatcher", "Reverend Martin Luther King Jr.", "Hon. Jane Doe", "Sir Isaac Newton", "Dame Judi Dench", "Mr. President", "Lady Macbeth", "Dr. Jane Goodall", "Ms. Sarah Connor", "Professor John Smith", "Captain Jack Sparrow", "Queen Elizabeth II", "King Arthur Pendragon", "Senator Kamala Harris", "Ambassador Samantha Power", "Judge Judy Sheindlin", "Admiral Horatio Nelson", "General Dwight D. Eisenhower", "Colonel Sanders", "Mayor Bill de Blasio", "Sheriff Joe Arpaio", "Governor Gavin Newsom", "Chancellor Angela Merkel", "Prime Minister Justin Trudeau", "Secretary of State Hillary Clinton", "Treasurer Janet Yellen", "Commodore Matthew Perry", "Baron von Richthofen", "Count Dracula", "Duke Ellington", "Viscount Montgomery", "Earl Grey", "Marquis de Lafayette", "Princess Diana Spencer", "Queen Victoria", "King Louis XIV", "Tsar Nicholas II", "Pope Francis",
		},
		Contexts: []string{
			"Literary fiction", "Legal documents", "Government forms", "Wedding invitations", "Email signatures", "Business correspondence", "Historical biographies", "Phone directories", "Genealogical records", "Conference badges", "Social media profiles", "Employee databases", "Obituaries", "Academic publications", "Event programs", "Hospital patient records", "School yearbooks", "Membership lists", "Personal blogs", "Customer databases", "Job applications", "Military rosters", "Restaurant reservations", "Online retail accounts", "Contact forms", "Television credits", "Book dedications", "Conference attendees lists", "Professional license registries", "Census data sheets", "Public speaking engagements", "Charity event donors lists", "Sports team rosters", "Political campaign materials", "Community service records", "Public health surveys", "Local government meeting minutes", "Public transportation schedules", "Cultural heritage documentation", "Public art installations", "City planning documents", "Environmental impact assessments", "Public service announcements", "Emergency contact forms", "Volunteer organization registrations", "Event ticketing systems", "Online forum registrations", "E-commerce account setups", "Digital identity verification", "Public health records", "Emergency contact forms", "Community event flyers", "School field trip itineraries", "Local history archives", "Public art installations", "City planning documents",
		},
	},
	{
		Name: "ADDRESS",
		Desc: "The 'ADDRESS' tag is used to identify and classify any reference to a geographical location including full or partial details such as street names, city names, states, ZIP or postal codes. It is typically applied in contexts involving directions, location-based services, or when documenting places of residence or business. An address can be recognized by a combination of elements like a numeric street number followed by a street name, possibly including building names, city or town names, and abbreviations for states or provinces. It may also include postal codes, which are often numerical or alphanumeric sequences.",
		Examples: []string{
			"1600 Pennsylvania Avenue NW, Washington, DC 20500", "48-50 St John Street, London, EC1M 4DG, UK", "Shinjuku, Tokyo 160-0000, Japan", "1 Infinite Loop, Cupertino, CA 95014, USA", "500 Terry Francois St, San Francisco, CA 94158", "Rua do Catete 153, Rio de Janeiro, RJ, 22220-000, Brazil", "Calle de Atocha, 25, 28012 Madrid, Spain", "Amalienstraße 17, 80333 München, Germany", "Indira Gandhi International Airport, New Delhi, DL 110037, India", "Česká 11, Brno, 602 00, Czech Republic", "999/9 Rama 1 Road, Pathumwan, Bangkok 10330, Thailand", "Unit 4, 1-3 Central Avenue, Moorabbin VIC 3189, Australia", "Block 133, Toa Payoh Lorong 1, #01-02, Singapore", "4044 Rue de Bullion, Montréal, QC H2W 2C8, Canada", "Room 214, Hunter Building, Victoria University of Wellington, Kelburn Parade, Wellington 6012, New Zealand", "Mahatma Gandhi Road, Bengaluru, Karnataka 560001, India", "Apt. 45, 2300 Rue Saint-Dominique, Québec, QC G1L 5W4, Canada", "7 Rue de Rivoli, 75001 Paris, France", "Flat 5B, The Tower Building, 11 York Road, Waterloo, London SE1 7NX, UK", "Kampala Road, P.O Box 7191, Kampala, Uganda",
		},
		Contexts: []string{
			"Postal delivery services", "Customer database entries", "Real estate listings", "E-commerce shipping forms", "Travel itineraries", "Business registration forms", "Taxi dispatch logs", "Residential lease agreements", "Property sale contracts", "Online map services", "Event invitations", "Hotel bookings", "Airbnb listings", "Government census records", "Driving directions", "Package tracking systems", "Utility bills", "Online shopping carts", "Customs declaration forms", "Insurance policy documents", "Medical appointment reminders", "Restaurant reservations", "Public transportation schedules", "Emergency contact forms", "Venue booking confirmations", "University application forms", "International shipping labels", "Building access logs", "Local government service requests", "Community bulletin boards", "Neighborhood association records", "Public health surveys", "Charity donation forms", "School enrollment forms", "Library membership applications", "Event registration forms", "Conference attendee lists", "Volunteer sign-up sheets", "Public records requests", "Online forum profiles", "Social media location tags", "Local business directories", "Public transportation route maps", "City planning documents", "Environmental impact assessments",
		},
	},
	{
		Name: "COMPANY",
		Desc: "The COMPANY tag identifies the official name of a business entity or organization. This tag is applied to text where the keyword refers explicitly to a recognized, formal business or non-profit entity, including corporations, institutions, and multinational organizations. Recognizable patterns include names followed by corporate designations such as Ltd., Corp., Inc., PLC, or clear relational identifiers like \"Group\" or \"Association.\" Use this tag for entries that denote established brands or entities involved in commerce, industry, politics, or public services, ensuring the entity is widely acknowledged and operates under a legal framework or regulatory body.",
		Examples: []string{
			"Apple Inc.", "The Coca-Cola Company", "British Broadcasting Corporation (BBC)", "Amazon.com, Inc.", "United Nations Children's Fund (UNICEF)", "The National Aeronautics and Space Administration (NASA)", "Tesla, Inc.", "Vodafone Group Plc", "Sony Corporation", "World Health Organization (WHO)", "Samsung Electronics Co., Ltd.", "MasterCard International Incorporated", "Alphabet Inc.", "Lloyd's Banking Group", "Shell Oil Company", "The World Bank Group", "Toyota Motor Corporation", "The Red Cross", "Harvard University", "American Heart Association, Inc.", "The Walt Disney Company", "Pfizer Inc.", "International Business Machines Corporation (IBM)", "The Goldman Sachs Group, Inc.", "The Bank of England", "The British Museum", "The Royal Society for the Prevention of Cruelty to Animals (RSPCA)", "The International Monetary Fund (IMF)", "The World Wildlife Fund (WWF)", "The International Olympic Committee (IOC)", "The European Union (EU)", "The United Nations Educational, Scientific and Cultural Organization (UNESCO)",
		},
		Contexts: []string{
			"Business press releases", "Corporate filings", "Annual reports", "Company websites", "Industry news articles", "Legal contracts", "Economic research papers", "Market analysis reports", "Investor presentations", "Business directories", "Government registrations", "Product catalogs", "Corporate interviews", "Trade publications", "Executive biographies", "Partnership announcements", "Conference brochures", "Marketing case studies", "Media press kits", "Venture capital pitches", "Stock market reports", "Company profiles", "Regulatory filings", "Public service announcements", "Non-profit newsletters", "Competition analysis", "Industry awards", "Corporate social responsibility reports", "Business school case studies", "Trade association publications", "Economic development reports", "Business networking events", "Corporate sponsorship announcements", "Industry conferences", "Business incubator programs", "Startup accelerators", "Business mentorship programs", "Corporate training materials", "Business podcasts and webinars", "Industry white papers", "Business blogs and vlogs",
		},
	},
	{
		Name: "DATE",
		Desc: "The 'DATE' tag is used to identify and categorize textual references to calendar dates, which may appear in multiple formats. Typical applications include tagging content that specifies a particular day, month, and year. This tag should be applied whenever a piece of text denotes a specific point in time using formats such as numeric (e.g., '2023-01-01'), written month and day (e.g., 'January 1, 2023'), or slash-separated numbers (e.g., '01/01/2023'). Recognizable patterns include sequences with numeric days and months, inclusion of full month names, or common date separators like hyphens and slashes.",
		Examples: []string{
			"31/12/2023", "April 25, 2024", "2024-04-25", "07-04-2025", "07/04/2025", "July 4, 2025", "November 11, 2040", "2040-11-11", "11/11/40", "03-03-2030", "2030/03/03", "December 31, 1999", "1999-12-31", "12/31/1999", "March 15th, 2021", "August 1st, 2022", "2022/08/01", "08/01/22", "February 29, 2020", "2020-02-29", "01-01-2021", "2021/01/01", "January 1, 2021", "2021-01-01", "01/01/21", "February 14, 2023", "2023-02-14", "14/02/23",
		},
		Contexts: []string{
			"Legal documents", "Event invitations", "Historical analysis papers", "Financial reports", "Email correspondence", "Blog posts", "Newspaper articles", "Social media updates", "Project timelines", "Birth certificates", "Weather forecasts", "Travel itineraries", "Academic journals", "Research datasets", "Medical records", "Appointment reminders", "Meeting minutes", "Shipping receipts", "Government announcements", "TV schedules", "Literary narratives", "Software logs", "Marketing schedules", "Helpdesk tickets", "Holiday greetings", "Inventory lists", "Digital photo metadata", "Calendars", "Personal diaries", "News bulletins", "Public service announcements", "Conference schedules", "Sports event listings", "Cultural heritage records", "Public health advisories", "Community event flyers", "School calendars", "University course schedules", "Corporate training materials", "Product release notes", "Online forums and discussions",
		},
	},
	{
		Name: "EMAIL",
		Desc: "The 'EMAIL' tag is used to identify email addresses within text data. This tag is typically applied when parsing or processing documents, databases, or communication logs where email addresses need to be highlighted or extracted. Recognizable patterns for this tag include strings that contain an '@' symbol separating a local part from a domain, usually followed by a top-level domain such as .com, .org, or .net. Email addresses often begin with alphanumeric characters and may include dots, underscores, or hyphens before and after the '@' symbol. This tag facilitates organization, communication routing, and data validation tasks.",
		Examples: []string{
			"jane_doe@university.edu", "contact-us@website.org", "support_team@enterprise.co", "a1234567@student.school.net", "feedback@community.biz", "sales-department@retailstore.com", "user.name@subdomain.service.com", "editorial@news-agency.co.uk", "hr-recruitment@organization.gov", "user+notifications@platform.com", "mail@host.org.mx", "me-email@hosting-site.global", "service_providers@network.int", "official.mail@ministry.in", "hello@domain.com.au", "inquiry@e-commerce.store", "staff_contacts@conference-event.info", "main-office@mailserver.co.jp", "personal_account@blogsphere.info", "admin.alerts@security.net",
		},
		Contexts: []string{
			"Customer service records", "Business correspondence", "Mailing lists", "Database exports", "Online inquiry forms", "User registration data", "Event RSVP confirmations", "Company newsletters", "Subscription services", "Technical support logs", "Job application portals", "Financial transaction reports", "Social media profiles", "Contact information forms", "Healthcare patient records", "Government communication logs", "E-commerce order confirmations", "Educational institution directories", "Conference attendee lists", "Marketing campaign data", "CRM system entries", "Network security alerts", "Website contact pages", "Internal HR documentation",
		},
	},
	{
		Name: "ID_NUMBER",
		Desc: "The ID_NUMBER tag is used to identify sequences of characters that represent unique personal or official identification numbers issued by governmental or authoritative institutions. These numbers can include Social Security Numbers (e.g., 123-45-6789), driver’s license numbers (e.g., DL#987654321), passport numbers (e.g., A1234567), and other similar identifiers. This tag is typically applied in databases, forms, or documents where personal identification is relevant. Common patterns to recognize ID_NUMBERs include specific formats like dashes, prefixes (e.g., DL#), and a combination of letters and digits that follow standard issuing conventions.",
		Examples: []string{
			"SSN: 876-54-3210", "Passport No: B7654321", "DL: NY1234567", "Employee ID: EID-457896", "National ID: 8976-543210", "Tax ID: TIN 456-78-9123", "Voter ID: VID12345678", "Health ID: H-123-456-789", "Student ID: SID20234567", "Security ID: SEC9876543", "Insurance ID: INS-123-456-7890", "Bank Account: BA0000123456", "University ID: U12345678", "Library Card: LC4567890123", "Membership ID: MEM1234567", "Corporate ID: CID0987654", "Citizen Number: CZN0983217", "Government ID: GOV-109283", "Military ID: MIL123456", "Work Permit: WP-09876",
		},
		Contexts: []string{
			"Government databases", "Healthcare forms", "Job applications", "Tax documents", "Employee records", "Financial statements", "Vehicle registrations", "University admissions", "Insurance claims", "Property deeds", "Voting registration", "Library records", "Criminal background checks", "Border crossing documents", "Bank account applications", "Utility company records", "Travel visa applications", "Military enlistment forms", "Online service registration", "Telecommunications accounts", "Law enforcement reports", "Social housing applications", "Corporate identity records", "Student transcript requests", "Professional certification forms", "Airline passenger lists", "Shipping and customs forms", "Professional networking profiles", "Membership applications", "Raffle or contest entries", "Public service applications", "Community service records", "Volunteer organization registrations", "Event ticketing systems", "Online forum registrations", "E-commerce account setups", "Digital identity verification", "Public health records", "Emergency contact forms",
		},
	},
	{
		Name: "LOCATION",
		Desc: "The LOCATION tag is used to identify and label any geographic entities. This includes names of cities, countries, continents, landmarks, and other notable sites. Typically applied in text referring to specific places, this tag helps categorize data for geographic indexing, search optimization, or context clarification. Recognizable patterns include names capitalized as proper nouns, often preceded by prepositions like 'in', 'at', or 'near', and sometimes followed by additional context like country or region (e.g., 'Paris, France'). This aids in distinguishing them from non-geographical entities.",
		Examples: []string{
			"Tokyo", "River Nile", "Grand Canyon", "Berlin, Germany", "Rio de Janeiro", "Eiffel Tower", "Sahara Desert", "Sydney Opera House", "Amazon Rainforest", "Vienna", "Ganges River", "Vatican City", "Mount Kilimanjaro", "Antarctica", "Washington, D.C.", "Taj Mahal", "Pyrenees Mountains", "Himalayas", "Siberia", "Yellowstone National Park", "Great Wall of China", "Niagara Falls", "Mount Everest", "Lake Baikal", "Istanbul, Turkey", "Cape Town, South Africa", "Machu Picchu, Peru", "Dubai, UAE", "Santorini, Greece", "Grand Canyon, USA", "Great Barrier Reef, Australia", "Stonehenge, UK", "Petra, Jordan", "Galápagos Islands, Ecuador", "Bora Bora, French Polynesia", "Banff National Park, Canada", "Mount Fuji, Japan", "Angkor Wat, Cambodia", "Serengeti National Park, Tanzania", "Acropolis of Athens, Greece", "Pyramids of Giza, Egypt", "Christ the Redeemer, Brazil", "Colosseum, Italy"},
		Contexts: []string{
			"Travel blogs", "News articles", "Geography textbooks", "Tourism brochures", "Navigation apps", "History books", "Weather reports", "Event invitations", "Travel itineraries", "Real estate listings", "Field study reports", "Adventure novels", "Documentaries", "Conference agendas", "City guides", "Public transport maps", "Museum directories", "Online encyclopedias", "Cultural heritage sites", "Monument plaques", "Diplomatic correspondence", "Geopolitical analyses", "Logistics plans", "Census data", "Business expansion reports", "Streaming travel shows", "Celebrity sightings", "Local government records", "Environmental impact studies", "Urban planning documents", "Cultural festivals", "Public health advisories", "Emergency response plans", "Community service announcements", "Public transportation schedules", "Local business directories", "Academic research papers", "Public health surveys", "Cultural heritage preservation", "Tourist attraction reviews", "Local news reports", "City council meeting minutes", "Public service announcements", "Community event flyers", "School field trip itineraries", "Local history archives", "Public art installations", "City planning documents",
		},
	},
	{
		Name: "PHONENUMBER",
		Desc: "The PHONENUMBER tag identifies sequences of digits formatted to represent telephone numbers, typically consisting of an area code, local exchange, and subscriber number. This tag applies when text strings match conventional phone number formats, including international and domestic prefixes, parentheses for area codes, or hyphens and spaces as separators. Common indicators are numeric strings starting with a '+' for country code, patterns like (123) 456-7890, or sequences featuring consistent segment separators like dashes. Apply this tag when the text aims to convey contact information for telecommunication purposes, ensuring accurate recognition of numbers for parsing and processing.",
		Examples: []string{
			"+44 20 7946 0958", "(555) 867-5309", "800.555.2946", "123 456 7890", "+91-22-27774194", "+81 (0)3 1234 5678", "01-4949-5969", "(02) 1234 5678", "+61-2-9876-5432", "+49 (0) 30 123456", "020 7946 0958", "+55 11 91234-5678", "+33 1 42 68 53 00", "1-800-273-8255", "1 234-567-8901", "0800 123 4567", "+234 703 123 4567", "212 555 0198", "+852 9876 5432", "+971 4 123 4567", "02-1234-5678", "+34 91 123 45 67", "1 (800) 555-0199", "0800 123 4567", "+61 2 9876 5432", "1-800-555-0199", "+1 (202) 456-1111", "+44 (0)20 7946 0958", "+49 (0)30 12345678", "+81 (0)3-1234-5678", "+33 1 42 68 53 00", "+55 (11) 91234-5678",
		},
		Contexts: []string{
			"Contact forms", "Business cards", "Email signatures", "Telephone directories", "Customer service documents", "Marketing brochures", "SMS messages", "Online ad listings", "Event invitations", "Website footers", "Digital contact lists", "User account settings", "Support chat transcripts", "Mobile app interfaces", "Emergency contact notices", "Reservation confirmations", "Voicemail transcriptions", "User profile pages", "Terms of service agreements", "Corporate press releases", "Government contact lists", "Public service announcements", "Community bulletin boards", "Local business directories", "Public health advisories", "School enrollment forms", "Library membership applications", "Event registration forms", "Conference attendee lists", "Volunteer sign-up sheets", "Public records requests", "Online forum registrations", "E-commerce account setups", "Digital identity verification", "Public health records", "Emergency contact forms", "Community event flyers", "School field trip itineraries", "Local history archives", "Public art installations", "City planning documents",
		},
	},
	{
		Name: "URL",
		Desc: "The 'URL' tag is designated for strings that represent Uniform Resource Locators, commonly known as web addresses. This tag applies to instances when a string identifies the location of a resource on the internet, accessible via web browsers. Signals of a URL include combinations of protocol identifiers like 'http://' or 'https://', domain names with extensions such as '.com', '.org', or '.net', and specific path structures. Application of this tag is appropriate in contexts involving web navigation, linking resources, or referencing online content, such as in articles, emails, or software documentation. Recognizable patterns include 'www' prefixes or domain names followed by TLDs (Top-Level Domains).",
		Examples: []string{
			"http://www.museumofmodernart.org/exhibitions", "https://secure.login.microsoft.com", "ftp://ftp.mozilla.org/pub/mozilla.org/firefox/releases/", "mailto:support@company.org", "https://docs.python.org/3/tutorial/index.html", "http://www.weather.gov/alerts", "https://subdomain.example-business.co.uk/services", "ftp://example.org/downloads", "https://en.wikipedia.org/wiki/Natural_language_processing", "http://localhost:8000/users", "https://shop.example.shoppingcart.de/products/", "http://company-intranet.net/internal/dashboard", "https://researchportal.edu/papers", "http://username:password@blog.example.com", "https://www.github.com/username/repository", "file:///C:/Users/Username/Documents/report.html", "https://api.serviceprovider.com/v1/users", "http://192.168.0.1/settings", "https://www.travelagency.travel/destinations/asia", "https://landingpage.socialnetwork.com/register?referral=12345",
		},
		Contexts: []string{
			"Web page content", "Email communication", "Software documentation", "Social media posts", "Academic references", "E-commerce listings", "Blog articles", "Online advertisements", "Technical manuals", "FAQ sections", "User guides", "Digital marketing materials", "Online newspaper articles", "Code repositories", "Corporate websites", "Educational websites", "Event announcements", "Product catalogs", "Online booking systems", "Online forums", "Digital newsletters", "Online surveys", "Public service announcements", "Community bulletin boards", "Local business directories", "Public health advisories", "School enrollment forms", "Library membership applications", "Event registration forms", "Conference attendee lists", "Volunteer sign-up sheets", "Public records requests", "Online forum registrations", "E-commerce account setups", "Digital identity verification", "Public health records", "Emergency contact forms", "Community event flyers", "School field trip itineraries", "Local history archives", "Public art installations", "City planning documents",
		},
	},
	{
		Name: "CARD_NUMBER",
		Desc: "The CARD_NUMBER tag identifies numeric sequences representing credit or debit card numbers, commonly seen in financial data. This tag is applied to strings of digits that follow specific patterns, typically 13 to 19 digits in length, often grouped into blocks of four with spaces or dashes. Examples include '4111 1111 1111 1111' or '5500-1234-5678-9010'. Recognizing this tag requires familiarity with typical card number structures such as Visa, MasterCard, or AMEX. Use this tag to isolate sensitive financial information that requires protection or processing in transaction data and personal information handling.",
		Examples: []string{
			"1234 5678 9123 4567", "3782-822463-10005", "6011-2435-6778-1221", "3056 9309 0259 04", "3530-1197-3210-018", "6759 4585 7694 0080 9", "4012-8888-8888-1881", "4556-7543-2343-2349", "3461 111111 11119", "6223-4525-6788-0019 8", "4916-6412-3412-3439", "5018 639388 05381 9", "6767 9867 1234 5678", "6011-0009-9013-9424", "4040-5689-1102-1054", "5594 7571 2345 6784", "5593-3312-1224-4567", "5038 1330 0289 1225", "3625 1234 5678 9012", "4903-7110-5511-0005", "ending in 0004", "XXXX-XXXX-XXXX-1234",
		},
		Contexts: []string{
			"Bank statements", "Online purchase receipts", "Credit card applications", "Payment processing logs", "E-commerce transaction data", "POS machine outputs", "Subscription forms", "Loan agreements", "Mobile payment apps", "Tax filing documents", "Budget tracking spreadsheets", "Fraud detection systems", "Customer service transcripts", "Billing notifications", "Monthly financial reports", "Insurance claim forms", "Utility bill payments", "Business invoices", "Password recovery emails", "Account registration forms", "Travel booking confirmations", "Retail store receipts", "Corporate expense reports", "Financial audits", "Investment account statements", "Digital wallet transactions", "Gift card balances", "Charity donation receipts", "Membership fee payments", "Online gaming transactions", "Public service announcements", "Community bulletin boards", "Local business directories", "Public health advisories", "School enrollment forms", "Library membership applications", "Event registration forms", "Conference attendee lists", "Volunteer sign-up sheets", "Public records requests", "Online forum registrations", "E-commerce account setups", "Digital identity verification", "Public health records", "Emergency contact forms", "Community event flyers", "School field trip itineraries", "Local history archives", "Public art installations", "City planning documents",
		},
	},
	{
		Name: "CREDIT_SCORE",
		Desc: "The CREDIT_SCORE tag represents numerical or descriptive evaluations of a person's creditworthiness, typically used in financial contexts. This tag should be applied when the text includes a specific credit score number, such as 700 or 750, or a qualitative credit rating term like 'Excellent', 'Good', or 'Poor'. Credit scores are usually found in financial reports, loan applications, and credit assessments. To recognize it, look for statements or contexts discussing credit evaluations or involving financial terms related to a person's credit profile or borrowing capability.",
		Examples: []string{
			"750", "Excellent", "700", "Good", "620", "Fair", "580", "Poor", "720", "Very Good", "800", "Exceptional", "650", "Average", "500", "Below Average", "550", "Subprime", "680", "Prime", "730",
		},
		Contexts: []string{
			"Credit reports", "Loan applications", "Mortgage documents", "Car loan evaluations", "Credit card applications", "Financial newsletters", "Bank statements", "Credit repair guides", "Online banking platforms", "Consumer finance blogs", "Personal finance books", "Investor presentations", "Risk assessment profiles", "Credit counseling sessions", "Debt management plans", "Business loan reviews", "Underwriting reports", "Mobile banking alerts", "Consumer credit alerts", "Financial advisory websites", "Credit monitoring services", "Credit score improvement seminars", "Retail financing offers",
		},
	},
	{
		Name: "LICENSE_PLATE",
		Desc: "The LICENSE_PLATE tag is used to identify and categorize alphanumeric codes that serve as unique identifiers for vehicles. These sequences often contain a combination of letters and numbers, formatted based on regional or national standards, such as 'XYZ-5678' or 'ABC1234'. This tag is typically applied in contexts where vehicle information is recorded, such as traffic citations, parking databases, or vehicle registration systems. Recognizable by their distinct format, license plates generally appear as concise strings prefixed or suffixed by letters, often separated by a dash or space, and are intended for vehicular identification.",
		Examples: []string{
			"A1 BCD 345", "B5678-YZ", "C123 D45", "KL-9876", "LMN 1234", "ZXC-076", "987 GHJ", "UIO-A123", "3456-DFG", "PRS-789T", "3R4 T56", "WQZ 2180", "9BN XF72", "YTZ-PO17", "TR 098 XZ", "QWERTY 6789", "1F2G-7H8", "VCV-123E", "NM 3456 OP", "5 AB C678",
		},
		Contexts: []string{
			"Traffic violation records", "Parking ticket issuances", "Vehicle registration forms", "Automated toll systems", "Surveillance camera footage", "Rental car agreements", "Stolen vehicle reports", "Insurance claim documents", "Border crossing records", "Airport parking logs", "Car dealership inventories", "Accident report filings", "Public road safety audits", "Cargo shipment documents", "Vehicle service histories", "Fleet management reports", "Emergency response logs", "Road maintenance schedules", "City planning records", "Highway monitoring systems", "Event parking passes", "Public transportation vehicle logs", "Local government vehicle databases", "Environmental impact assessments", "Public service announcements", "Community bulletin boards", "Local business directories", "Public health advisories", "School enrollment forms", "Library membership applications", "Event registration forms", "Conference attendee lists", "Volunteer sign-up sheets", "Public records requests", "Online forum registrations", "E-commerce account setups", "Digital identity verification", "Public health records", "Emergency contact forms", "Community event flyers", "School field trip itineraries", "Local history archives", "Public art installations", "City planning documents",
		},
	},
	{
		Name: "SSN",
		Desc: "The 'SSN' tag is used to identify Social Security Numbers, which are unique nine-digit identifiers assigned to U.S. citizens and eligible residents. It is typically applied when such numbers appear in documents, online forms, or databases. An SSN follows a specific pattern: three digits, a hyphen, two digits, another hyphen, and ending with four digits (e.g., 987-65-4320). Indicators for tagging include a sequence of numbers in this format within text associated with personal identity verification, financial records, or employment information. This tag is crucial for ensuring data privacy and regulatory compliance.",
		Examples: []string{
			"123-45-6789", "987-65-4320", "111-22-3333", "555-44-3333", "999-88-7777", "222-33-4444", "444-55-6666", "888-77-9999", "000-11-2222", "333-66-7777", "666-77-8888", "777-88-9999", "123-12-1234", "456-78-9012", "789-01-2345",
		},
		Contexts: []string{
			"Personal identity documents", "Financial applications", "Employment forms", "Online registration portals", "Government paperwork", "Loan application forms", "Tax return documents", "Medical records", "Background check reports", "Legal contracts", "Credit history files", "Insurance claims", "Pension benefit statements", "University enrollment forms", "Military service records", "Real estate transactions", "Bank account openings", "Tenant screening forms", "Welfare benefit applications", "Driver's license records", "Corporate HR files", "Mortgage processing forms", "Identity verification systems",
		},
	},
	{
		Name: "VIN",
		Desc: "The 'VIN' tag is used to identify Vehicle Identification Numbers, which are unique codes assigned to every motor vehicle when it's manufactured. These alphanumeric sequences typically consist of 17 characters, without using the letters I, O, or Q to avoid confusion with numbers 1 and 0. This tag is applied when referencing specific details about a vehicle's identity, such as in service records, vehicle registrations, or insurance documents. Recognizable by their consistent length and mixed use of letters and numbers, VIN sequences generally follow standard formatting conventions acknowledged globally.",
		Examples: []string{
			"1HGCM82633A123456", "1FTRX18W51NA12345", "1C4RJFAG8FC123456", "5NPE34C23H123456", "1G1ZT628XFF123456", "1FAFP404X1F123456", "2C4RC1BG3ER123456", "1N4AL3AP7FC123456", "3VW2K7AJ5FM123456", "1GNSKJE74FR123456", "1FTRX18W51NA12345", "1C4RJFAG8FC123456", "5NPE34C23H123456", "1G1ZT628XFF123456", "1FAFP404X1F123456", "2C4RC1BG3ER123456", "1N4AL3AP7FC123456", "3VW2K7AJ5FM123456", "1GNSKJE74FR123456", "1FTRX18W51NA12345", "1C4RJFAG8FC123456",
		},
		Contexts: []string{
			"Vehicle auction listings", "Owner's manual documentation", "Law enforcement reports", "Vehicle compliance paperwork", "Maintenance invoices", "History reports", "Legal verification documents", "Spare parts catalogs", "Insurance documents", "Registration papers", "Service records", "Warranty claims", "Vehicle emissions certifications", "Theft tracking systems", "Accident reports", "Chassis engraving", "Component matching guides", "Fleet management systems", "Online dealership inventories", "Vehicle recall notifications", "Auto transportation paperwork", "DMV registration forms", "Manufacturing records", "Vehicle export/import documentation", "Lease agreements", "Car rental agreements", "Vehicle financing contracts", "Insurance underwriting documents", "Roadside assistance records", "Vehicle inspection reports", "Public service announcements", "Community bulletin boards", "Local business directories",
		},
	},
}
