# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plugin/proto/model.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'plugin/proto/model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18plugin/proto/model.proto\x12\x05proto\"\"\n\x0ePredictRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\"2\n\x0fPredictResponse\x12\x1f\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\r.proto.Entity\"(\n\x13PredictBatchRequest\x12\x11\n\tsentences\x18\x01 \x03(\t\"C\n\x14PredictBatchResponse\x12+\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x16.proto.PredictResponse\"A\n\x06\x45ntity\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05start\x18\x03 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x05\">\n\x07TagInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x65xamples\x18\x03 \x03(\t\"(\n\x06Sample\x12\x0e\n\x06tokens\x18\x01 \x03(\t\x12\x0e\n\x06labels\x18\x02 \x03(\t\"_\n\x0f\x46inetuneRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x1c\n\x04tags\x18\x02 \x03(\x0b\x32\x0e.proto.TagInfo\x12\x1e\n\x07samples\x18\x03 \x03(\x0b\x32\r.proto.Sample\"#\n\x10\x46inetuneResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"/\n\x0bSaveRequest\x12\x0b\n\x03\x64ir\x18\x01 \x01(\t\x12\x13\n\x0b\x65xport_onnx\x18\x02 \x01(\x08\"\x1f\n\x0cSaveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xf8\x01\n\x05Model\x12\x38\n\x07Predict\x12\x15.proto.PredictRequest\x1a\x16.proto.PredictResponse\x12G\n\x0cPredictBatch\x12\x1a.proto.PredictBatchRequest\x1a\x1b.proto.PredictBatchResponse\x12;\n\x08\x46inetune\x12\x16.proto.FinetuneRequest\x1a\x17.proto.FinetuneResponse\x12/\n\x04Save\x12\x12.proto.SaveRequest\x1a\x13.proto.SaveResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin.proto.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_PREDICTREQUEST']._serialized_start=35
  _globals['_PREDICTREQUEST']._serialized_end=69
  _globals['_PREDICTRESPONSE']._serialized_start=71
  _globals['_PREDICTRESPONSE']._serialized_end=121
  _globals['_PREDICTBATCHREQUEST']._serialized_start=123
  _globals['_PREDICTBATCHREQUEST']._serialized_end=163
  _globals['_PREDICTBATCHRESPONSE']._serialized_start=165
  _globals['_PREDICTBATCHRESPONSE']._serialized_end=232
  _globals['_ENTITY']._serialized_start=234
  _globals['_ENTITY']._serialized_end=299
  _globals['_TAGINFO']._serialized_start=301
  _globals['_TAGINFO']._serialized_end=363
  _globals['_SAMPLE']._serialized_start=365
  _globals['_SAMPLE']._serialized_end=405
  _globals['_FINETUNEREQUEST']._serialized_start=407
  _globals['_FINETUNEREQUEST']._serialized_end=502
  _globals['_FINETUNERESPONSE']._serialized_start=504
  _globals['_FINETUNERESPONSE']._serialized_end=539
  _globals['_SAVEREQUEST']._serialized_start=541
  _globals['_SAVEREQUEST']._serialized_end=588
  _globals['_SAVERESPONSE']._serialized_start=590
  _globals['_SAVERESPONSE']._serialized_end=621
  _globals['_MODEL']._serialized_start=624
  _globals['_MODEL']._serialized_end=872
# @@protoc_insertion_point(module_scope)
